#!/usr/bin/perl5.6.0

use lib qw( /usr/lib/perl5/site_perl/5.6.1/i686-linux/ );
use Pg;

$conn = Pg::connectdb("dbname=testdb");
die $conn->errorMessage unless PGRES_CONNECTION_OK eq $conn->status;

$result = $conn->exec( "CREATE TABLE ref_reference_by ( joinkey TEXT, ref_reference_by TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_checked_out ( joinkey TEXT, ref_checked_out TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_cgc ( joinkey TEXT, ref_cgc INTEGER, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_pmid ( joinkey TEXT, ref_pmid INTEGER, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_med ( joinkey TEXT, ref_med INTEGER, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_author ( joinkey TEXT, ref_author TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_title ( joinkey TEXT, ref_title TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_journal ( joinkey TEXT, ref_journal TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_volume ( joinkey TEXT, ref_volume INTEGER, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_pages ( joinkey TEXT, ref_pages TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_year ( joinkey TEXT, ref_year INTEGER, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_abstract ( joinkey TEXT, ref_abstract TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_hardcopy ( joinkey TEXT, ref_hardcopy TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_pdf ( joinkey TEXT, ref_pdf TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_html ( joinkey TEXT, ref_html TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_tif ( joinkey TEXT, ref_tif TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE TABLE ref_lib ( joinkey TEXT, ref_lib TEXT, ref_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP )");
$result = $conn->exec( "CREATE INDEX ref_reference_by_idx ON ref_reference_by ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_checked_out_idx ON ref_checked_out ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_cgc_idx ON ref_cgc ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_pmid_idx ON ref_pmid ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_med_idx ON ref_med ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_author_idx ON ref_author ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_title_idx ON ref_title ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_journal_idx ON ref_journal ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_volume_idx ON ref_volume ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_pages_idx ON ref_pages ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_year_idx ON ref_year ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_abstract_idx ON ref_abstract ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_hardcopy_idx ON ref_hardcopy ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_pdf_idx ON ref_pdf ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_html_idx ON ref_html ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_tif_idx ON ref_tif ( joinkey )");
$result = $conn->exec( "CREATE INDEX ref_lib_idx ON ref_lib ( joinkey )");
$result = $conn->exec( "GRANT ALL ON ref_reference_by TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_checked_out TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_cgc TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_pmid TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_med TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_author TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_title TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_journal TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_volume TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_pages TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_year TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_abstract TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_hardcopy TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_pdf TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_html TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_tif TO nobody");
$result = $conn->exec( "GRANT ALL ON ref_lib TO nobody");
