#!/usr/bin/perl

use strict;

my %hash;

$/ = '';
my $infile = 'phenotype_to_GO_group_edited.txt';
open (IN, "<$infile") or die "Cannot open $infile : $!";
while (my $para = <IN>) {
  my ($phen) = $para =~ m/\n(WBPhenotype\d+) /;
  $hash{$phen} = $para;
} # while (my $para = <IN>)
close (IN) or die "Cannot close $infile : $!";

$/ = "\n";
$infile = 'body';
open (IN, "<$infile") or die "Cannot open $infile : $!";
while (my $line = <IN>) {
  if ($line =~ m/^> (WBPhenotype\d+)/) {
    my $phen = $1;
    if ($hash{$phen}) { print "$hash{$phen}\n"; }
      else { print "ERR no match for $phen\n\n"; }
  }
} # while (my $para = <IN>)
close (IN) or die "Cannot close $infile : $!";


__END__
phenotype_to_GO_group_edited.txt

MATCH cell_development_abnormal -- cell_development
WBPhenotype0000529 cell_development_abnormal
GO:0048468 cell development
GeneOnt Definition	"The process whose specific outcome is the progression of the cell over time, from its formation to the mature structure. Cell development does not include the steps involved in committing a cell to a specific fate."

MATCH organ_system_development_abnormal -- system_development
WBPhenotype0000530 organ_system_development_abnormal
GO:0048731 system development
GeneOnt Definition	"The process whose specific outcome is the progression of an organismal system over time, from its formation to the mature structure. A system is a regularly interacting or interdependent group of organs or tissues that work together to carry out a given biological process."


body  

Hi Juancarlos,

Here is a list of phenotype terms in descending order of frequency of  
use.  When you have the time, it would help a lot to have Carol's  
phenotype to GO mappings (attached file) sorted based on the list  
below (in message).  There are supposed to be ~400 terms on Carol's  
list, which we will ultimately be manually checking for accuracy and  
we would like to prioritize her list by "importance" of WBPhenotype  
term, which in this case refers to the number of times the term has  
been used.

There is no rush on this.  We won't be meeting to go over these  
mappings until January or maybe even until February as Ranjana will be  
away until then.  I just wanted to send this off before I forgot.

Thanks for your help.

Karen




Begin forwarded message:

> From: Igor Antoshechkin <igor.antoshechkin@caltech.edu>
> Date: 19 December 2007 17:59:54 PST
> To: Karen Yook <kyook@caltech.edu>
> Subject: Re: Fwd: help with sorting Fwd: Phenotype to GO mappings
>
> Here is another version with RNAi and Variation counts separately,  
> just in case.
>
> Igor.
>
>>
>>> *From: *Karen Yook <kyook@imap-server.its.caltech.edu <mailto:kyook@imap-server.its.caltech.edu 
>>> >>
>>> *Date: *13 December 2007 16:12:15 PST
>>> *To: *Igor Antoshechkin <igor.antoshechkin@caltech.edu <mailto:igor.antoshechkin@caltech.edu 
>>> >>
>>> *Subject: **help with sorting Fwd: Phenotype to GO mappings*
>>>
>>> Hi Igor,
>>> Will you help me with a wormbase query?  I would like a list in  
>>> descending order of the most used Phenotype terms (including  
>>> WBPhenotype ID and WBPhenotype term) in Wormbase.  These would  
>>> include terms assigned to RNAi and all variations.
>>> The ultimate goal is to use this list to prioritize our work on  
>>> the Phenotype to GO mappings generated by Carol a while back.
>>> Thanks for your help.  Karen
>>>
>>>
>>> ~~~~
>>> Karen Yook
>>>
>>> WormBase Curator
>>> http://www.wormbase.org
>>> Tel: 626.395.8325
>>> e-mail: kyook@caltech.edu <mailto:kyook@caltech.edu>
>>>
>>>
>>>
>>>
>>>
>>> Begin forwarded message:
>>>
>>>> *From: *azurebrd@ugcs.caltech.edu  
>>>> <mailto:azurebrd@ugcs.caltech.edu>
>>>> *Date: *13 December 2007 05:00:29 PST
>>>> *To: *"Karen Yook" <kyook@imap-server.its.caltech.edu <mailto:kyook@imap-server.its.caltech.edu 
>>>> >>
>>>> *Cc: *ranjana@its.caltech.edu <mailto:ranjana@its.caltech.edu>,  
>>>> "Kimberly Van Auken" <vanauken@caltech.edu <mailto:vanauken@caltech.edu 
>>>> >>, "gary schindelman" <garys@caltech.edu  
>>>> <mailto:garys@caltech.edu>>, "Jolene" <jolenef@caltech.edu <mailto:jolenef@caltech.edu 
>>>> >>, "Raymond Lee" <raymond@caltech.edu  
>>>> <mailto:raymond@caltech.edu>>
>>>> *Subject: **Re: Phenotype to GO mappings*
>>>>
>>>> Could you give me a shortcut and let me know which fields on  
>>>> which forms
>>>> you mean when you say ``frequency of use of the WBPhenotype# in  
>>>> RNAi and
>>>> variation curation combined'' ?  Thanks =)
>>>>
>>>> Thanks, Japan is going well, today we went to the Folk Craft  
>>>> museum and
>>>> saw a temporary exhibit on Indian textiles (not the most  
>>>> fascinating thing
>>>> as far as I was concerned), then later in the day I took a yoga  
>>>> class that
>>>> was half in japanese, half in english, half very relaxing and  
>>>> meditative,
>>>> half really hard and tiring ;  it was an interesting experience.
>>>>
>>>> Juancarlos
>>>>
>>>>> Hi Juancarlos,
>>>>>
>>>>> I was asked to see if you would help us prioritize a list of  
>>>>> phenotype
>>>>> terms for our GO mappings.
>>>>> I've attached the list below.  What we need is for the list to be
>>>>> sorted based on frequency of use of
>>>>> the WBPhenotype# in RNAi and variation curation combined.
>>>>>
>>>>> There is no rush.   Thanks for any help.
>>>>>
>>>>> Karen
>>>>> P.S. I hope Japan treated you well!
>>>>>
>>>>>
>
>
> -- 
>
> Igor Antoshechkin, Ph.D.
> http://www.WormBase.org/
> California Institute of Technology
> Division of Biology 156-29
> Pasadena, CA 91125
> Tel: 626.395.5878
>
> PhenotypeID	Phenotype_Name	Total	RNAi	Variation
> WBPhenotype0000050	embryonic_lethal	6194	6151	43
> WBPhenotype0000031	slow_growth	2011	1989	22
> WBPhenotype0000059	larval_arrest	1809	1805	4
> WBPhenotype0000643	locomotion_abnormal	1645	1535	110
> WBPhenotype0000689	maternal_sterile	1512	1512	0
> WBPhenotype0000688	sterile	981	275	706
> WBPhenotype0000269	unclassified	913	913	0
> WBPhenotype0000054	larval_lethal	898	885	13
> WBPhenotype0001037	sterile_progeny	772	772	0
> WBPhenotype0000697	protruding_vulva	729	696	33
> WBPhenotype0001183	fat_content_reduced	688	687	1
> WBPhenotype0000062	lethal	679	21	658
> WBPhenotype0000535	organism_morphology_abnormal	552	552	0
> WBPhenotype0000154	reduced_brood_size	494	427	67
> WBPhenotype0000583	dumpy	463	400	63
> WBPhenotype0000017	aldicarb_resistant	414	412	2
> WBPhenotype0000032	sick	411	410	1
> WBPhenotype0000038	exploded_through_vulva	307	302	5
> WBPhenotype0000640	egg_laying_abnormal	292	287	5
> WBPhenotype0000229	small	250	212	38
> WBPhenotype0000061	extended_life_span	244	232	12
> WBPhenotype0000679	transgene_subcellular_localization_abnormal	238	 
> 233	5
> WBPhenotype0001010	clear	201	201	0
> WBPhenotype0000006	egg_laying_defective	176	8	168
> WBPhenotype0001184	fat_content_increased	165	156	9
> WBPhenotype0000729	cell_death_abnormal	154	151	3
> WBPhenotype0000700	multivulva	150	86	64
> WBPhenotype0001236	transgene_expression_increased	150	149	1
> WBPhenotype0000365	embryo_osmotic_integrity_abnormal_early_emb	145	 
> 144	1
> WBPhenotype0000039	life_span_abnormal	144	143	1
> WBPhenotype0000644	paralyzed	144	114	30
> WBPhenotype0000055	early_larval_arrest	135	131	4
> WBPhenotype0000057	early_larval_lethal	134	111	23
> WBPhenotype0000255	amphid_phasmid_morphology_abnormal	128	4	124
> WBPhenotype0000270	pleiotropic_defects_severe_early_emb	127	127	0
> WBPhenotype0000646	sluggish	125	99	26
> WBPhenotype0000195	distal_tip_cell_migration_abnormal	121	115	6
> WBPhenotype0001102	mitotic_spindle_abnormal_early_emb	118	115	3
> WBPhenotype0000164	thin	111	98	13
> WBPhenotype0000772	sister_chromatid_segregation_abnormal_early_emb	 
> 107	107	0
> WBPhenotype0000022	long	107	88	19
> WBPhenotype0001413	bacterially_unswollen	106	0	106
> WBPhenotype0001029	patchy_coloration	92	92	0
> WBPhenotype0000541	cord_commissures_fail_to_reach_target	90	90	0
> WBPhenotype0001143	multiple_nuclei_early_emb	87	86	1
> WBPhenotype0001340	egg_laying_imipramine_resistant	84	0	84
> WBPhenotype0000436	protein_subcellular_localization_abnormal	83	73	10
> WBPhenotype0000638	molt_defect	82	80	2
> WBPhenotype0000698	vulvaless	78	21	57
> WBPhenotype0000056	late_larval_arrest	77	77	0
> WBPhenotype0000776	passage_through_meiosis_abnormal_early_emb	74	73	1
> WBPhenotype0000060	adult_lethal	72	70	2
> WBPhenotype0000228	spontaneous_mutation_rate_increased	71	71	0
> WBPhenotype0000025	blistered	69	62	7
> WBPhenotype0000976	ventral_cord_patterning_abnormal	69	69	0
> WBPhenotype0001175	high_incidence_male_progeny	68	60	8
> WBPhenotype0000843	male_mating_efficiency_reduced	67	0	67
> WBPhenotype0001152	pronuclear_migration_abnormal_early_emb	63	62	1
> WBPhenotype0000632	axon_fasciculation_abnormal	62	60	2
> WBPhenotype0001080	excessive_blebbing_early_emb	60	60	0
> WBPhenotype0001020	embryonic_lethal_late_emb	60	59	1
> WBPhenotype0000126	general_pace_of_development_abnormal_early_emb	58	 
> 58	0
> WBPhenotype0001538	mRNA_surveillance_defective	54	0	54
> WBPhenotype0001036	sterile_F1	52	52	0
> WBPhenotype0001018	cytokinesis_abnormal_emb	51	51	0
> WBPhenotype0001132	ectopic_cleavage_furrows_early_emb	51	49	2
> WBPhenotype0000691	gonad_development_abnormal	50	49	1
> WBPhenotype0000306	transgene_expression_abnormal	50	45	5
> WBPhenotype0001082	large_cytoplasmic_granules_early_emb	49	49	0
> WBPhenotype0000012	dauer_constitutive	49	0	49
> WBPhenotype0000040	one_cell_arrest_early_emb	46	23	23
> WBPhenotype0000823	germ_line_proliferation_abnormal	45	43	2
> WBPhenotype0001013	pathogen_susceptibility_increased	45	45	0
> WBPhenotype0001105	P0_spindle_position_abnormal_early_emb	45	45	0
> WBPhenotype0000594	cell_migration_abnormal	44	39	5
> WBPhenotype0000773	chromosome_segregation_abnormal	43	40	3
> WBPhenotype0000456	touch_resistant	42	0	42
> WBPhenotype0001068	egg_laying_serotonin_resistant	41	1	40
> WBPhenotype0001130	cytokinesis_fails_early_emb	41	39	2
> WBPhenotype0001106	spindle_orientation_abnormal_AB_or_P1_early_emb	 
> 40	40	0
> WBPhenotype0001224	axon_outgrowth_abnormal	40	0	40
> WBPhenotype0000007	bag_of_worms	40	1	39
> WBPhenotype0001119	cell_cycle_slow_early_emb	39	38	1
> WBPhenotype0001126	cell_cell_contacts_abnormal_four_emb	39	39	0
> WBPhenotype0001139	nuclear_reassembly_abnormal_early_emb	38	37	1
> WBPhenotype0000470	HSN_migration_abnormal	38	0	38
> WBPhenotype0001077	 
> chromosome_segregation_abnormal_karyomeres_early_emb	37	37	0
> WBPhenotype0001414	male_mating_defective	36	0	36
> WBPhenotype0000425	antibody_staining_reduced	36	0	36
> WBPhenotype0001156	pronuclear_size_abnormal_early_emb	36	36	0
> WBPhenotype0000045	developmental_delay_postembryonic	35	35	0
> WBPhenotype0000070	male_tail_morphology_abnormal	35	15	20
> WBPhenotype0000637	dauer_formation_abnormal	35	19	16
> WBPhenotype0000183	apoptosis_increased	35	31	4
> WBPhenotype0001121	exaggerated_asynchrony_early_emb	34	34	0
> WBPhenotype0000645	roller	34	27	7
> WBPhenotype0000058	late_larval_lethal	33	27	6
> WBPhenotype0001034	pronuclear_nuclear_appearance_abnormal_early_emb	 
> 32	29	3
> WBPhenotype0000013	dauer_defective	32	0	32
> WBPhenotype0000565	coiler	31	0	31
> WBPhenotype0001165	excess_maternal_pronucleus_early_emb	31	30	1
> WBPhenotype0000186	oogenesis_abnormal	30	29	1
> WBPhenotype0001041	meiosis_abnormal_early_emb	30	30	0
> WBPhenotype0000885	engulfment_abnormal	30	2	28
> WBPhenotype0001261	pale	30	30	0
> WBPhenotype0000030	growth_abnormal	29	27	2
> WBPhenotype0000745	transposon_silencing_abnormal	29	29	0
> WBPhenotype0001083	multiple_cytoplasmic_cavities_early_emb	28	28	0
> WBPhenotype0000384	axon_guidance_abnormal	28	15	13
> WBPhenotype0001155	pronuclei_meet_centrally_early_emb	27	27	0
> WBPhenotype0000545	egg_retention	27	0	27
> WBPhenotype0001147	polar_body_abnormal_early_emb	27	27	0
> WBPhenotype0000683	masculinization_of_germline	27	14	13
> WBPhenotype0001044	cortical_dynamics_abnormal_early_emb	27	27	0
> WBPhenotype0001011	complex_phenotype_early_emb	27	27	0
> WBPhenotype0001141	nucleus_reforms_cell_division_remnant_early_emb	 
> 27	27	0
> WBPhenotype0001171	shortened_life_span	26	16	10
> WBPhenotype0000501	left_handed_roller	26	0	26
> WBPhenotype0006001	squashed_vulva	26	0	26
> WBPhenotype0000469	Q_neuroblast_lineage_migration_abnormal	25	0	25
> WBPhenotype0000081	L1_arrest	24	16	8
> WBPhenotype0000760	spindle_orientation_abnormal_early_emb	24	24	0
> WBPhenotype0001384	fertility_reduced	24	2	22
> WBPhenotype0001435	ammonium_chloride_chemotaxis_defective	23	0	23
> WBPhenotype0001339	egg_laying_levamisole_resistant	23	0	23
> WBPhenotype0001341	egg_laying_phentolamine_resistant	23	0	23
> WBPhenotype0000687	feminization_of_XX_and_XO_animals	23	23	0
> WBPhenotype0000198	vulval_precursor_cell_induction_abnormal	23	0	23
> WBPhenotype0001516	cuticle_helicity_abnormal	22	0	22
> WBPhenotype0001278	transgene_expression_reduced	22	19	3
> WBPhenotype0000414	cell_fate_transformation	22	0	22
> WBPhenotype0001177	embryo_osmotic_pressure_sensitive_early_emb	22	22	0
> WBPhenotype0000634	pharyngeal_pumping_abnormal	22	4	18
> WBPhenotype0000749	embryonic_development_abnormal	22	21	1
> WBPhenotype0001038	tumorous_germline	22	22	0
> WBPhenotype0000042	slow_embryonic_development	21	21	0
> WBPhenotype0000670	spermatogenesis_abnormal	20	1	19
> WBPhenotype0001150	polar_body_reabsorbed_one_two_early_emb	20	20	0
> WBPhenotype0000699	vulva_development_abnormal	20	3	17
> WBPhenotype0000019	pharyngeal_pumping_reduced	20	1	19
> WBPhenotype0000052	maternal_effect_lethal_emb	19	1	18
> WBPhenotype0001134	Aba_ABp_division_axis_abnormal_early_emb	19	19	0
> WBPhenotype0000867	embryonic_arrest	19	17	2
> WBPhenotype0001127	EMS_anterior_extension_fails_early_emb	19	19	0
> WBPhenotype0001530	cephalic_sensillum_morphology_abnormal	19	0	19
> WBPhenotype0001517	annulae_morphology_abnormal	19	0	19
> WBPhenotype0001212	cuticle_fragile	19	0	19
> WBPhenotype0000046	pace_of_P_lineage_abnormal_early_emb	19	19	0
> WBPhenotype0000748	asymmetric_cell_division_abnormal_early_emb	19	18	1
> WBPhenotype0000709	pharyngeal_morphology_abnormal	18	18	0
> WBPhenotype0001411	cuticle_carbohydrate_surface_abnormal	18	0	18
> WBPhenotype0001535	deirid_sensillum_morphology_abnormal	18	0	18
> WBPhenotype0000663	osmotic_avoidance_abnormal	18	2	16
> WBPhenotype0001410	protein_expression_absent	18	2	16
> WBPhenotype0000505	male_ray_morphology_abnormal	17	1	16
> WBPhenotype0000628	spindle_assembly_abnormal_early_emb	17	17	0
> WBPhenotype0001123	synchronous_second_division_early_emb	17	17	0
> WBPhenotype0001014	pathogen_resistance_increased	17	2	15
> WBPhenotype0001515	struts_abnormal	17	0	17
> WBPhenotype0000354	cell_differentiation_abnormal	16	0	16
> WBPhenotype0000961	pattern_of_transgene_expression_abnormal	16	8	8
> WBPhenotype0000220	vulva_cell_fate_specification_abnormal	16	16	0
> WBPhenotype0000247	sodium_chemotaxis_defective	16	0	16
> WBPhenotype0000367	comma_arrest_emb	16	2	14
> WBPhenotype0000051	embryonic_terminal_arrest_variable_emb	16	16	0
> WBPhenotype0000112	protein_expression_abnormal	16	16	0
> WBPhenotype0000254	chloride_chemotaxis_defective	16	0	16
> WBPhenotype0000227	male_turning_abnormal	16	1	15
> WBPhenotype0001109	P0_spindle_rotation_delayed_early_emb	15	15	0
> WBPhenotype0000779	late_embryonic_arrest	15	4	11
> WBPhenotype0000767	 
> integrity_of_membranous_organelles_abnormal_early_emb	15	15	0
> WBPhenotype0000775	meiosis_abnormal	14	11	3
> WBPhenotype0001220	cell_death_sexually_dimorphic_increased	14	0	14
> WBPhenotype0001108	P0_spindle_rotation_failure_early_emb	14	14	0
> WBPhenotype0000708	intestinal_development_abnormal	14	13	1
> WBPhenotype0000181	axon_trajectory_abnormal	14	0	14
> WBPhenotype0000762	spindle_position_abnormal_early_emb	14	8	6
> WBPhenotype0000216	cell_fate_specification_abnormal	14	5	9
> WBPhenotype0001438	odorant_positive_chemotaxis_defective	14	0	14
> WBPhenotype0000020	pharyngeal_pumping_irregular	14	0	14
> WBPhenotype0001084	sodium_chloride_chemotaxis_defective	14	0	14
> WBPhenotype0001412	alae_morphology_abnormal	13	0	13
> WBPhenotype0001297	male_tail_development_abnormal	13	0	13
> WBPhenotype0000302	benzaldehyde_chemotaxis_defective	13	0	13
> WBPhenotype0000765	spindle_elongation_integrity_abnormal_early_emb	 
> 13	13	0
> WBPhenotype0001275	increased_genetic_pathway_signal	13	0	13
> WBPhenotype0000120	protein_expression_reduced	13	7	6
> WBPhenotype0000684	fewer_germ_cells	13	13	0
> WBPhenotype0000746	cell_division_abnormal	13	11	2
> WBPhenotype0001310	neuron_positioning_abnormal	13	1	12
> WBPhenotype0000768	cytoplasmic_structure_abnormal_early_emb	13	13	0
> WBPhenotype0001227	commissure_absent	12	0	12
> WBPhenotype0001136	embryonic_morphology_abnormal	12	12	0
> WBPhenotype0001026	nuclear_morphology_alteration_early_emb	12	11	1
> WBPhenotype0001512	loss_of_left_right_asymmetry	12	0	12
> WBPhenotype0001416	pathogen_adherence_defect	12	0	12
> WBPhenotype0000695	vulva_morphology_abnormal	12	3	9
> WBPhenotype0001298	hindgut_morphology_abnormal	12	0	12
> WBPhenotype0000731	germ_cell_hypersensitive_ionizing_radiation	12	10	2
> WBPhenotype0001030	pronuclear_envelope_abnormal_early_emb	12	11	1
> WBPhenotype0001168	pseudocleavage_absent_early_emb	11	10	1
> WBPhenotype0000651	constipated	11	7	4
> WBPhenotype0000002	kinker	11	0	11
> WBPhenotype0000256	amphid_morphology_abnormal	11	0	11
> WBPhenotype0001260	oocyte_morphology_abnormal	11	2	9
> WBPhenotype0000304	isoamyl_alcohol_chemotaxis_defective	11	0	11
> WBPhenotype0000862	bloated	11	0	11
> WBPhenotype0000710	intestinal_morphology_abnormal	11	11	0
> WBPhenotype0001426	coelomocyte_uptake_defective	11	8	3
> WBPhenotype0000502	right_handed_roller	11	0	11
> WBPhenotype0001113	P1_aster_abnormal_early_emb	10	10	0
> WBPhenotype0000026	lipid_depleted	10	10	0
> WBPhenotype0001124	ABa_ABp_EMS_synchronous_division_early_emb	10	10	0
> WBPhenotype0000138	lipid_composition_abnormal	10	9	1
> WBPhenotype0000615	cilia_morphology_abnormal	9	0	9
> WBPhenotype0001100	early_embryonic_lethal	9	9	0
> WBPhenotype0001276	ectopic_expression_transgene	9	8	1
> WBPhenotype0001163	pronucleus_formation_failure_early_emb	9	9	0
> WBPhenotype0001169	pseudocleavage_exaggerated_early_emb	9	9	0
> WBPhenotype0001182	fat_content_abnormal	9	0	9
> WBPhenotype0000316	touch_resistant_tail	9	0	9
> WBPhenotype0000409	organism_morphology_variable	9	9	0
> WBPhenotype0001161	maternal_pronucleus_indistinct_early_emb	9	9	0
> WBPhenotype0000696	everted_vulva	9	8	1
> WBPhenotype0001209	skiddy	9	0	9
> WBPhenotype0001282	mitochondrial_metabolism_abnormal	9	9	0
> WBPhenotype0000324	short	9	0	9
> WBPhenotype0000771	centrosome_attachment_abnormal_early_emb	9	9	0
> WBPhenotype0001284	coenzyme_Q_depleted	9	9	0
> WBPhenotype0000478	isothermal_tracking_behavior_abnormal	9	0	9
> WBPhenotype0001125	P2_EMS_synchronous_division_early_emb	9	9	0
> WBPhenotype0000044	egg_size_abnormal_early_emb	9	9	0
> WBPhenotype0001534	neuronal_ECM_abnormal	9	0	9
> WBPhenotype0000309	SDS_sensitive_dauer	9	7	2
> WBPhenotype0001497	mitotic_metaphase_to_anaphase_transition_defect	9	 
> 0	9
> WBPhenotype0004004	male_response_to_contact_defective	9	8	1
> WBPhenotype0001110	aster_abnormal_early_emb	9	9	0
> WBPhenotype0000179	neuron_degeneration	9	0	9
> WBPhenotype0000349	flaccid	9	0	9
> WBPhenotype0001131	loose_mitotic_furrow_early_emb	9	9	0
> WBPhenotype0000067	organism_stress_response_abnormal	9	9	0
> WBPhenotype0000717	gene_expression_abnormal	8	0	8
> WBPhenotype0000812	germ_cell_development_abnormal	8	5	3
> WBPhenotype0000411	rod_like_larval_lethal	8	0	8
> WBPhenotype0000159	dauer_arrest_abnormal	8	1	7
> WBPhenotype0000668	endomitotic_oocytes	8	6	2
> WBPhenotype0000077	cuticle_shedding_abnormal	8	0	8
> WBPhenotype0001408	pattern_protein_expression_abnormal	8	4	4
> WBPhenotype0000407	ray_loss	8	1	7
> WBPhenotype0000793	posterior_body_morphology_abnormal	8	8	0
> WBPhenotype0000694	hermaphrodite_sterile	8	0	8
> WBPhenotype0000071	head_morphology_abnormal	8	1	7
> WBPhenotype0001239	mating_latency_increased	8	0	8
> WBPhenotype0000863	male_fertility_reduced	8	1	7
> WBPhenotype0000297	rays_fused	8	8	0
> WBPhenotype0000703	epithelial_morphology_abnormal	8	7	1
> WBPhenotype0001107	spindle_rotation_abnormal_early_emb	8	8	0
> WBPhenotype0000093	lineage_abnormal	8	7	1
> WBPhenotype0001153	pronuclear_migration_failure_early_emb	7	7	0
> WBPhenotype0000157	posterior_body_wall_contraction_abnormal	7	6	1
> WBPhenotype0000115	anterior_pharynx_abnormal	7	7	0
> WBPhenotype0000553	muscle_ultrastructure_disorganized	7	0	7
> WBPhenotype0000474	muscle_attachment_abnormal	7	5	2
> WBPhenotype0000005	hyperactive_egg_laying	7	0	7
> WBPhenotype0000926	body_wall_muscle_morphology_abnormal	7	2	5
> WBPhenotype0001085	butanone_chemotaxis_defective	7	0	7
> WBPhenotype0000586	bleach_hypersensitive	7	0	7
> WBPhenotype0001415	pathogen_adherence_abnormal	7	0	7
> WBPhenotype0000661	solitary_feeding_increased	7	0	7
> WBPhenotype0000563	shrinker	7	0	7
> WBPhenotype0000660	social_feeding_increased	6	0	6
> WBPhenotype0001129	cleavage_furrow_abnormal_early_emb	6	4	2
> WBPhenotype0001329	curly	6	0	6
> WBPhenotype0000761	spindle_position_orientation_abnormal_early_emb	6	 
> 6	0
> WBPhenotype0000053	paralyzed_arrested_elongation_two_fold	6	5	1
> WBPhenotype0000707	pharyngeal_development_abnormal	6	6	0
> WBPhenotype0000373	egg_shape_variable	6	6	0
> WBPhenotype0000424	antibody_staining_abnormal	6	0	6
> WBPhenotype0001046	pharyngeal_muscle_morphology_abnormal	6	0	6
> WBPhenotype0000905	neuron_morphology_abnormal	6	1	5
> WBPhenotype0000129	temperature_induced_dauer_formation_defective	6	0	6
> WBPhenotype0000666	ovulation_abnormal	6	5	1
> WBPhenotype0000648	male_mating_abnormal	6	0	6
> WBPhenotype0000224	serotonin_deficient	6	0	6
> WBPhenotype0000088	body_muscle_displaced	6	6	0
> WBPhenotype0000145	fertility_abnormal	6	5	1
> WBPhenotype0001277	transformer	6	1	5
> WBPhenotype0000142	cell_stress_response_abnormal	6	6	0
> WBPhenotype0001223	germline_RNAi_resistant	6	0	6
> WBPhenotype0001509	rays_missing	6	6	0
> WBPhenotype0000674	slow_development	6	1	5
> WBPhenotype0000234	dopamine_deficient	6	0	6
> WBPhenotype0000777	polar_body_extrusion_abnormal_early_emb	6	5	1
> WBPhenotype0000613	reproductive_system_physiology_abnormal	6	6	0
> WBPhenotype0000642	hyperactive	6	6	0
> WBPhenotype0001186	embryo_delayed_at_pronuclear_contact_early_emb	6	 
> 6	0
> WBPhenotype0000134	gene_expression_level_reduced	6	2	4
> WBPhenotype0001418	organism_hypersensitive_dessication	6	0	6
> WBPhenotype0001222	transposon_mutator	6	0	6
> WBPhenotype0000868	paralyzed_body	6	0	6
> WBPhenotype0001151	pronucleus_centrosomes_abnormal_early_emb	6	5	1
> WBPhenotype0000308	dauer_development_abnormal	6	4	2
> WBPhenotype0001333	neuron_cell_body_absent	5	0	5
> WBPhenotype0000848	developmental_delay	5	1	4
> WBPhenotype0001388	organism_hypersensitive_gamma_irradiation	5	4	1
> WBPhenotype0000605	reproductive_system_morphology_abnormal	5	5	0
> WBPhenotype0000119	protein_expression_increased	5	1	4
> WBPhenotype0000743	RNAi_response_abnormal	5	5	0
> WBPhenotype0000204	anterior_body_contraction_defective	5	0	5
> WBPhenotype0000288	distal_germline_abnormal	5	5	0
> WBPhenotype0000209	short_defecation_cycle	5	1	4
> WBPhenotype0000137	mRNA_levels_reduced	5	4	1
> WBPhenotype0000483	no_gut_granules	5	5	0
> WBPhenotype0001447	ammonium_chloride_adaptation_abnormal	5	0	5
> WBPhenotype0000275	organism_UV_hypersensitive	5	2	3
> WBPhenotype0001355	gonad_morphology_abnormal	5	5	0
> WBPhenotype0001237	ectopic_axon_outgrowth	5	0	5
> WBPhenotype0001292	body_wall_muscle_physiology_abnormal	5	0	5
> WBPhenotype0000303	diacetyl_chemotaxis_defective	5	0	5
> WBPhenotype0000759	spindle_abnormal_early_emb	5	4	1
> WBPhenotype0001033	proximal_germ_cell_proliferation_abnormal	5	2	3
> WBPhenotype0001043	interphase_entry_abnormal_early_emb	5	5	0
> WBPhenotype0000682	feminization_of_germline	5	5	0
> WBPhenotype0001078	cytokinesis_abnormal_early_emb	5	5	0
> WBPhenotype0000284	sperm_transfer_defective	5	2	3
> WBPhenotype0000249	osmotic_avoidance_defective	5	0	5
> WBPhenotype0001093	intestinal_physiology_abnormal	5	5	0
> WBPhenotype0001518	biogenic_amine_physiology_abnormal	5	0	5
> WBPhenotype0000257	phasmid_morphology_abnormal	5	0	5
> WBPhenotype0000724	protein_secretion_abnormal	5	5	0
> WBPhenotype0000495	ray_ectopic	5	4	1
> WBPhenotype0001445	sodium_acetate_adaptation_abnormal	5	0	5
> WBPhenotype0001213	locomotion_reduced	5	1	4
> WBPhenotype0000351	failure_to_hatch	5	4	1
> WBPhenotype0000829	Q_lineage_abnormal	5	0	5
> WBPhenotype0000421	levamisole_resistant	5	1	4
> WBPhenotype0000547	starved	5	0	5
> WBPhenotype0000330	pharyngeal_relaxation_defective	5	0	5
> WBPhenotype0000861	body_wall_muscle_development_abnormal	5	0	5
> WBPhenotype0001028	nuclear_appearance_abnormal	5	5	0
> WBPhenotype0001446	sodium_chloride_adaptation_abnormal	5	0	5
> WBPhenotype0000034	embryonic_polarity_abnormal	5	4	1
> WBPhenotype0000704	excretory_canal_morphology_abnormal	5	4	1
> WBPhenotype0000671	resistant_to_copper	4	0	4
> WBPhenotype0001219	cell_survival_sexually_dimorphic_increased_	4	0	4
> WBPhenotype0000744	transgene_induced_cosuppression_abnormal	4	4	0
> WBPhenotype0000242	body_elongation_defective	4	4	0
> WBPhenotype0000472	endoderm_absent	4	4	0
> WBPhenotype0000010	drug_hypersensitive	4	0	4
> WBPhenotype0000737	germ_cell_resistant_ionizing_radiation	4	3	1
> WBPhenotype0000301	distal_tip_cell_reflex_failure	4	0	4
> WBPhenotype0001428	intestinal_vacuole	4	3	1
> WBPhenotype0001502	chemical_resistant	4	0	4
> WBPhenotype0001024	male_morphology_abnormal	4	1	3
> WBPhenotype0000690	gonad_migration_abnormal	4	3	1
> WBPhenotype0000182	apoptosis_reduced	4	4	0
> WBPhenotype0000047	gastrulation_abnormal	4	4	0
> WBPhenotype0000121	translation_abnormal	4	0	4
> WBPhenotype0000412	octanol_chemotaxis_defective	4	1	3
> WBPhenotype0000406	lumpy	4	0	4
> WBPhenotype0000035	larval_body_morphology_abnormal	4	1	3
> WBPhenotype0001045	sporadic_pumping	4	0	4
> WBPhenotype0000650	defecation_abnormal	4	0	4
> WBPhenotype0000335	pharynx_slippery	4	0	4
> WBPhenotype0001401	mitochondria_morphology_abnormal	4	3	1
> WBPhenotype0001072	response_to_food_abnormal	4	0	4
> WBPhenotype0001302	P_granule_localization_abnormal	4	4	0
> WBPhenotype0001225	phasmid_socket_absent	4	0	4
> WBPhenotype0000122	post_translational_processing_abnormal	4	0	4
> WBPhenotype0001086	trimethylthiazole_chemotaxis_defective	4	0	4
> WBPhenotype0001194	ectopic_neuron	4	0	4
> WBPhenotype0001104	P0_spindle_absent_early_emb	4	4	0
> WBPhenotype0001158	pronuclear_breakdown_asynchronous_early_emb	4	4	0
> WBPhenotype0001504	maternal_effect_sterile	4	0	4
> WBPhenotype0000180	axon_morphology_abnormal	4	0	4
> WBPhenotype0001138	nucleus_abnormal_early_emb	4	4	0
> WBPhenotype0000334	isthmus_corpus_slippery	4	0	4
> WBPhenotype0000190	no_dauer_recovery	4	0	4
> WBPhenotype0000633	axon_branching_abnormal	4	0	4
> WBPhenotype0000170	precocious_alae	4	1	3
> WBPhenotype0000315	mechanosensation_abnormal	4	3	1
> WBPhenotype0000653	mechanosensory_system_abnormal	4	0	4
> WBPhenotype0000930	sexually_dimorphic_development_abnormal	4	0	4
> WBPhenotype0000473	progressive_paralysis	4	4	0
> WBPhenotype0001230	abnormal_anterior_cell_migration	3	0	3
> WBPhenotype0001328	posterior_body_dumpy	3	0	3
> WBPhenotype0001288	movement_reduced	3	0	3
> WBPhenotype0001012	organism_pathogen_response_abnormal	3	0	3
> WBPhenotype0000630	quinine_chemotaxis_defective	3	0	3
> WBPhenotype0000659	feeding_behavior_abnormal	3	3	0
> WBPhenotype0000073	tail_morphology_abnormal	3	1	2
> WBPhenotype0000298	rays_displaced	3	3	0
> WBPhenotype0000475	muscle_detached	3	3	0
> WBPhenotype0000706	gut_granule_biogenesis_reduced	3	0	3
> WBPhenotype0000114	mRNA_expression_abnormal	3	3	0
> WBPhenotype0000150	starvation_induced_dauer_formation_defective	3	0	3
> WBPhenotype0000730	apoptosis_abnormal	3	3	0
> WBPhenotype0000146	organism_temperature_response_abnormal	3	2	1
> WBPhenotype0000104	cell_polarity_abnormal	3	2	1
> WBPhenotype0000314	scrawny	3	1	2
> WBPhenotype0001354	cytoskeleton_filament_morphology_abnormal	3	3	0
> WBPhenotype0000983	fertilization_defective	3	2	1
> WBPhenotype0001346	cytoskeleton_dynamic_abnormal	3	3	0
> WBPhenotype0000085	swollen_intestine	3	1	2
> WBPhenotype0001231	intraflagellar_transport_accelerated	3	0	3
> WBPhenotype0001241	ray_fusion	3	0	3
> WBPhenotype0001385	precocious_oogenesis	3	2	1
> WBPhenotype0000750	larval_development_abnormal	3	3	0
> WBPhenotype0000673	brood_size_abnormal	3	0	3
> WBPhenotype0000893	male_germ_line_proliferation_abnormal	3	2	1
> WBPhenotype0000379	head_notched	3	1	2
> WBPhenotype0000769	cytoplasmic_appearance_abnormal_early_emb	3	3	0
> WBPhenotype0001021	male_sexual_development_abnormal	3	0	3
> WBPhenotype0001351	protein_phosphorylation_reduced	3	2	1
> WBPhenotype0001431	pointed_tail_tip_male	3	0	3
> WBPhenotype0001486	unfolded_protein_accumulation	3	3	0
> WBPhenotype0000747	pharyngeal_contraction_defective	3	0	3
> WBPhenotype0000083	L3_arrest	3	1	2
> WBPhenotype0000966	germline_mortal	3	0	3
> WBPhenotype0000816	neuron_development_abnormal	3	0	3
> WBPhenotype0000175	hypercontracted	3	0	3
> WBPhenotype0001265	head_movement_abnormal	3	3	0
> WBPhenotype0001528	sensillum_accessory_cell_morphology_abnormal	3	0	3
> WBPhenotype0000892	hermaphrodite_germ_line_proliferation_abnormal	3	 
> 2	1
> WBPhenotype0000082	L2_arrest	3	1	2
> WBPhenotype0001352	endoplasmic_reticulum_metabolism_abnormal	3	3	0
> WBPhenotype0000999	athermotactic	3	0	3
> WBPhenotype0000300	amphid_sheath_cell_morphology_abnormal	3	0	3
> WBPhenotype0001264	peroxisome_physiology_abnormal	3	3	0
> WBPhenotype0000251	octopamine_deficient	3	0	3
> WBPhenotype0001176	one_cell_shape_abnormal_early_emb	3	3	0
> WBPhenotype0000219	vulval_cell_induction_reduced	3	3	0
> WBPhenotype0001336	no_male_progeny	3	0	3
> WBPhenotype0000675	zygotic_lethal	3	0	3
> WBPhenotype0000117	L1_lethal	3	0	3
> WBPhenotype0000904	muscle_cell_morphology_abnormal	3	3	0
> WBPhenotype0000996	expulsion_defective	3	0	3
> WBPhenotype0001510	neuronal_cell_fate_specification_abnormal	3	0	3
> WBPhenotype0000283	vulva_uterus_connection_defective	3	2	1
> WBPhenotype0000206	autosomal_nondisjunction_meiosis	3	0	3
> WBPhenotype0001498	sperm_pseudopod_physiology_abnormal	3	0	3
> WBPhenotype0000172	cell_proliferation_increased	3	3	0
> WBPhenotype0000202	alae_abnormal	3	3	0
> WBPhenotype0000352	backing_uncoordinated	3	0	3
> WBPhenotype0001027	nuclear_position_abnormal_early_emb	3	3	0
> WBPhenotype0001216	meiosis_metaphase_to_anaphase_transition_block	2	 
> 0	2
> WBPhenotype0000540	muscle_arm_development_abnormal	2	0	2
> WBPhenotype0000963	male_pigmentation_abnormal	2	0	2
> WBPhenotype0000878	chemosensory_neuron_development_abnormal	2	0	2
> WBPhenotype0000345	VPC_cell_division_abnormal	2	2	0
> WBPhenotype0001421	endocytic_transport_abnormal	2	0	2
> WBPhenotype0001343	meiotic_spindle_abnormal_early_emb	2	2	0
> WBPhenotype0001122	reversed_asynchrony_early_emb	2	2	0
> WBPhenotype0000491	isthmus_morphology_abnormal	2	0	2
> WBPhenotype0001419	emetine_hypersensitive	2	0	2
> WBPhenotype0000457	organism_starvation_hypersensitive	2	1	1
> WBPhenotype0000107	inhibition_of_ovulation_abnormal	2	2	0
> WBPhenotype0000888	male_behavior_abnormal	2	0	2
> WBPhenotype0000527	organism_pigmentation_abnormal	2	2	0
> WBPhenotype0000296	spicules_crumpled	2	1	1
> WBPhenotype0000072	body_morphology_abnormal	2	0	2
> WBPhenotype0000106	inhibition_of_oocyte_maturation_abnormal	2	2	0
> WBPhenotype0001167	pseudocleavage_abnormal_early_emb	2	2	0
> WBPhenotype0001112	aster_AB_resembles_P1_aster_early_emb	2	2	0
> WBPhenotype0001309	flat_locomotion_path	2	0	2
> WBPhenotype0001409	protein_expression_ectopic	2	2	0
> WBPhenotype0000964	DMPP_resistant	2	1	1
> WBPhenotype0000395	no_differentiated_gametes	2	2	0
> WBPhenotype0000685	larval_growth_slow	2	0	2
> WBPhenotype0001308	weak_pumping	2	0	2
> WBPhenotype0001524	quiescence_abnormal	2	0	2
> WBPhenotype0000864	early_elongation_arrest	2	0	2
> WBPhenotype0000948	cuticle_morphology_abnormal	2	0	2
> WBPhenotype0001494	distal_tip_cell_migration_precocious	2	0	2
> WBPhenotype0000928	male_physiology_abnormal	2	0	2
> WBPhenotype0001154	paternal_pronucleus_migrates_early_emb	2	2	0
> WBPhenotype0000603	muscle_system_morphology_abnormal	2	2	0
> WBPhenotype0001299	cell_division_abnormal_male	2	0	2
> WBPhenotype0001271	pathogen_induced_death_increased	2	2	0
> WBPhenotype0001166	 
> excess_paternal_pronucleus_abnormal_centrosome_early_emb	2	2	0
> WBPhenotype0000480	pyrazine_chemotaxis_defective	2	0	2
> WBPhenotype0001325	backing_not_sustained	2	0	2
> WBPhenotype0000770	embryonic_cell_morphology_abnormal	2	2	0
> WBPhenotype0000664	exaggerated_body_bends	2	0	2
> WBPhenotype0001145	polar_body_number_abnormal_early_emb	2	2	0
> WBPhenotype0000850	touch_resistant_anterior_body	2	0	2
> WBPhenotype0000233	dopamine_metabolism_abnormal	2	0	2
> WBPhenotype0000391	defecation_missing_motor_steps	2	0	2
> WBPhenotype0001207	protein_signaling_abnormal	2	0	2
> WBPhenotype0001006	pharyngeal_pumping_rate_abnormal	2	2	0
> WBPhenotype0001522	spicules_protrude	2	0	2
> WBPhenotype0000018	pharyngeal_pumping_increased	2	2	0
> WBPhenotype0001240	male_tail_sensory_ray_differentiation_abnormal	2	 
> 0	2
> WBPhenotype0000662	foraging_behavior_abnormal	2	0	2
> WBPhenotype0001533	outerlabial_morphology_abnormal	2	0	2
> WBPhenotype0001273	organism_heat_response_abnormal	2	0	2
> WBPhenotype0000127	dauer_recovery_abnormal	2	0	2
> WBPhenotype0000422	twitcher	2	0	2
> WBPhenotype0000780	shaker	2	0	2
> WBPhenotype0000702	epithelial_cell_fusion_failure	2	0	2
> WBPhenotype0001115	cell_cycle_timing_abnormal_early_emb	2	2	0
> WBPhenotype0000329	pumping_asynchronous	2	0	2
> WBPhenotype0000486	colchicine_hypersensitive	2	0	2
> WBPhenotype0000289	uterus_morphology_abnormal	2	2	0
> WBPhenotype0000441	tail_rounded	2	0	2
> WBPhenotype0000641	activity_level_abnormal	2	1	1
> WBPhenotype0001251	amphid_channel_axoneme_short	2	0	2
> WBPhenotype0001291	social_behavior_abnormal	2	1	1
> WBPhenotype0001532	innerlabial_morphology_abnormal	2	0	2
> WBPhenotype0000080	no_anterior_pharynx	2	2	0
> WBPhenotype0000611	muscle_system_physiology_abnormal	2	2	0
> WBPhenotype0000184	apoptosis_fails_to_occur	2	0	2
> WBPhenotype0000282	hermaphrodite_sex_muscle_development_abnormal	2	0	2
> WBPhenotype0000426	antibody_staining_increased	2	2	0
> WBPhenotype0001040	chemosensory_response_abnormal	2	0	2
> WBPhenotype0001221	nose_touch_defective	2	0	2
> WBPhenotype0000764	embryonic_cell_organization_biogenesis_abnormal	2	 
> 2	0
> WBPhenotype0001079	cytoplasmic_dynamics_abnormal_early_emb	2	2	0
> WBPhenotype0000133	expression_lipogenic_enzyme_reduced	2	2	0
> WBPhenotype0001296	lannate_resistant	2	0	2
> WBPhenotype0001208	RNAi_resistant	2	0	2
> WBPhenotype0000417	cell_division_failure	2	2	0
> WBPhenotype0000239	vulval_cell_lineage_abnormal	2	0	2
> WBPhenotype0001436	nose_touch_hypersensitive	2	0	2
> WBPhenotype0000066	hermaphrodite_specific_lethality	1	1	0
> WBPhenotype0000430	male_copulatory_structure_development_abnormal	1	 
> 0	1
> WBPhenotype0001294	head_bent	1	0	1
> WBPhenotype0004007	periodic_spicule_prodding_defective	1	1	0
> WBPhenotype0000163	clear_larva	1	1	0
> WBPhenotype0001235	cell_division_polarity_abnormal	1	0	1
> WBPhenotype0000028	RNA_processing_abnormal	1	1	0
> WBPhenotype0000907	anus_morphology_abnormal	1	0	1
> WBPhenotype0001242	intraflagellar_transport_slow	1	0	1
> WBPhenotype0000725	lipid_metabolism_abnormal	1	1	0
> WBPhenotype0000551	omega_turns	1	0	1
> WBPhenotype0001513	dense_core_vesicle_exocytosis_abnormal	1	0	1
> WBPhenotype0001565	lysine_chemotaxis_defective	1	0	1
> WBPhenotype0000290	sperm_absent	1	0	1
> WBPhenotype0000136	mRNA_levels_increased	1	1	0
> WBPhenotype0000902	intestinal_cell_morphology_abnormal	1	1	0
> WBPhenotype0000158	posterior_body_wall_shortened_interval	1	1	0
> WBPhenotype0001217	 
> germ_cell_mitosis_metaphase_to_anaphase_transition_block	1	0	1
> WBPhenotype0001248	wing_cilia_morphology_abnormal	1	0	1
> WBPhenotype0001420	biofilm_absent_head	1	0	1
> WBPhenotype0001379	organism_toxic_chemical_response_abnormal	1	1	0
> WBPhenotype0001508	anchor_cell_fusion_abnormal	1	1	0
> WBPhenotype0000105	oocyte_meiotic_maturation_abnormal	1	1	0
> WBPhenotype0001321	presynaptic_region_morphology_abnormal	1	0	1
> WBPhenotype0000361	lima_bean_arrest	1	1	0
> WBPhenotype0001280	transgene_expression_reduced_hermaphrodite	1	0	1
> WBPhenotype0000364	gut_granule_birefringence_misplaced	1	1	0
> WBPhenotype0001270	pathogen_induced_cell_death_reduced	1	1	0
> WBPhenotype0001097	premature_spermatocyte_germ_cell_differentiation	 
> 1	1	0
> WBPhenotype0000218	vulval_cell_induction_increased	1	0	1
> WBPhenotype0001135	embryonic_morphology_abnormal_early_emb	1	1	0
> WBPhenotype0001196	synchronization_calcium_signal_defective_pharynx	 
> 1	0	1
> WBPhenotype0001190	pharyngeal_physiology_abnormal	1	0	1
> WBPhenotype0001330	egg_laying_event_infrequent	1	0	1
> WBPhenotype0000866	germ_cell_arrest	1	0	1
> WBPhenotype0001295	body_twisted	1	0	1
> WBPhenotype0001520	abnormal_posterior_neuron_migration	1	1	0
> WBPhenotype0000881	cilia_mislocalized	1	0	1
> WBPhenotype0000065	male_specific_lethality	1	0	1
> WBPhenotype0000504	nuclear_division_abnormal	1	1	0
> WBPhenotype0000639	temperature_induced_dauer_formation_abnormal	1	0	1
> WBPhenotype0000443	spicule_morphology_abnormal	1	0	1
> WBPhenotype0000419	L3_lethal	1	0	1
> WBPhenotype0000102	presynaptic_vesicle_cluster_abnormal	1	0	1
> WBPhenotype0000962	level_of_transgene_expression_abnormal	1	1	0
> WBPhenotype0000631	drug_response_abnormal	1	0	1
> WBPhenotype0001525	terminal_bulb_morphology_abnormal	1	0	1
> WBPhenotype0001312	neuron_number_abnormal	1	1	0
> WBPhenotype0000273	thrashing_reduced	1	0	1
> WBPhenotype0001398	neurite_morphology_abnormal	1	0	1
> WBPhenotype0001199	gonad_sheath_contractions_abnormal	1	1	0
> WBPhenotype0001386	fertilization_defective_hermaphrodite	1	0	1
> WBPhenotype0000023	serotonin_hypersensitive	1	0	1
> WBPhenotype0000325	arecoline_hypersensitive	1	0	1
> WBPhenotype0000492	corpus_morphology_abnormal	1	0	1
> WBPhenotype0000386	genotoxic_induced_apoptosis_abnormal	1	0	1
> WBPhenotype0000015	positive_chemotaxis_defective	1	0	1
> WBPhenotype0001375	transgene_expression_undetectable	1	1	0
> WBPhenotype0001254	amphid_channel_cilia_bulbous	1	0	1
> WBPhenotype0000274	dead_eggs_laid	1	1	0
> WBPhenotype0000118	L2_lethal	1	0	1
> WBPhenotype0000311	semi_sterile	1	0	1
> WBPhenotype0001365	male_bursa_development_abnormal	1	0	1
> WBPhenotype00000688		1	0	1
> WBPhenotype0000148	starvation_induced_dauer_formation_abnormal	1	0	1
> WBPhenotype0001363	head_cavity	1	0	1
> WBPhenotype0001267	induced_contraction_rate_abnormal	1	1	0
> WBPhenotype0000778	feeding_inefficient	1	0	1
> WBPhenotype0000845	levamisole_response_abnormal	1	0	1
> WBPhenotype0000806	hermaphrodite_fertility_abnormal	1	1	0
> WBPhenotype0001035	nuclear_appearance_number_abnormal_early_emb	1	0	1
> WBPhenotype0000677	chemosensation_defective	1	0	1
> WBPhenotype0001060	AWC_odorant_chemotaxis_defective	1	0	1
> WBPhenotype0000241	accumulated_cell_corpses	1	1	0
> WBPhenotype0000341	imipramine_hypersensitive	1	0	1
> WBPhenotype0001390	cell_UV_hypersensitive	1	0	1
> WBPhenotype0000949	pseudocoelom_morphology_abnormal	1	0	1
> WBPhenotype0000189	hypodermis_disorganized	1	1	0
> WBPhenotype0000358	extra_cell_division_postembryonic	1	1	0
> WBPhenotype0004026	nose_touch_abnormal	1	0	1
> WBPhenotype0000915	pale_adult	1	1	0
> WBPhenotype0001433	precocious_cell_fusion	1	0	1
> WBPhenotype0000075	cuticle_attachment_abnormal	1	1	0
> WBPhenotype0000672	presynaptic_vesicle_cluster_localization_abnormal	 
> 1	0	1
> WBPhenotype0000616	synapse_morphology_abnormal	1	0	1
> WBPhenotype0001402	connected_mitochondria	1	0	1
> WBPhenotype0000978	spermatheca_physiology_abnormal	1	1	0
> WBPhenotype0001137	embryos_small_early_emb	1	1	0
> WBPhenotype0001255	wing_cilia_bulbous	1	0	1
> WBPhenotype0000286	embryo_disorganized	1	1	0
> WBPhenotype0000016	aldicarb_hypersensitive	1	0	1
> WBPhenotype0000188	gonad_arm_morphology_abnormal	1	1	0
> WBPhenotype0001193	disorganized_pharyngeal_EPG	1	0	1
> WBPhenotype0000101	UV_induced_apoptosis_increased	1	1	0
> WBPhenotype0001144	polar_body_number_size_early_emb	1	1	0
> WBPhenotype0000113	RNA_expression_abnormal	1	1	0
> WBPhenotype0000854	intraflagellar_transport_defective	1	0	1
> WBPhenotype0010004	part_of	1	1	0
> WBPhenotype0001442	sodium_acetate_chemotaxis_defective	1	0	1
> WBPhenotype0001432	over_retracted_male_tail	1	0	1
> WBPhenotype0001004	pharyngeal_relaxation_abnormal	1	0	1
> WBPhenotype0001506	spontaneous_reversal_rate_abnormal	1	0	1
> WBPhenotype0001128	EMS_anterior_extension_extreme_early_emb	1	1	0
> WBPhenotype0001422	endocytic_transport_defect	1	0	1
> WBPhenotype0004030	male_response_to_hermaphrodite_abnormal	1	0	1
> WBPhenotype0000711	organism_hypersensitive_ionizing_radiation	1	0	1
> WBPhenotype0000151	anterior_pharynx_extra_cells	1	0	1
> WBPhenotype0001098	no_rectum	1	1	0
> WBPhenotype0001347	intestinal_calcium_signaling_abnormal	1	1	0
> WBPhenotype0001228	alae_absent	1	0	1
> WBPhenotype0000368	one_point_five_fold_arrest_emb	1	1	0
> WBPhenotype0001178	egg_integrity_abnormal_early_emb	1	0	1
> WBPhenotype0000420	levamisole_hypersensitive	1	0	1
> WBPhenotype0001373	protein_rna_interaction_abolished	1	0	1
> WBPhenotype0001234	nonanone_chemotaxis_defective	1	0	1
> WBPhenotype0001096	protrusion_at_vulval_region	1	1	0
> WBPhenotype0001529	sensilium_sheath_cell_abnormal	1	0	1
> WBPhenotype0000884	morphology_AWB_abnormal	1	0	1
> WBPhenotype0000844	serotonin_induced_pumping_abnormal	1	0	1
> WBPhenotype0000979	spermatheca_dilation_defective	1	0	1
> WBPhenotype0001392	cell_cycle_arrest	1	0	1
> WBPhenotype0000090	epidermis_cuticle_detached	1	1	0
> WBPhenotype0001495	cell_division_precocious	1	0	1
> WBPhenotype0000033	developmental_timing_abnormal	1	1	0
> WBPhenotype0001317	evoked_postsynaptic_amplitude_reduced	1	0	1
> WBPhenotype0001334	hermaphrodite_sex_muscle_morphology_abnormal	1	0	1
> WBPhenotype0001397	necrotic_cell_death_increased	1	0	1
> WBPhenotype0000327	corpus_contraction_defect	1	0	1
> WBPhenotype0001536	embryonic_cell_patterning_abnormal	1	1	0
> WBPhenotype0001201	no_expulsion_defecation	1	0	1
> WBPhenotype0000128	temperature_induced_dauer_formation_increased	1	0	1
> WBPhenotype0000264	cAMP_chemotaxis_defective	1	0	1
> WBPhenotype0001200	gonad_sheath_contraction_rate_reduced	1	0	1
> WBPhenotype0000291	no_oocytes	1	1	0
> WBPhenotype0001368	spermatheca_absent	1	0	1
> WBPhenotype0000408	dauer_recovery_inhibited	1	0	1
> WBPhenotype0001263	peroxisome_morphology_abnormal	1	1	0
> WBPhenotype0000998	thermophilic	1	0	1
> WBPhenotype0000932	bis_phenol_A_hypersensitive	1	0	1
> WBPhenotype0001274	organism_heat_hypersensitive	1	1	0
> WBPhenotype0000461	paraquat_resistant	1	1	0
> WBPhenotype0000294	intestine_dark	1	0	1
> WBPhenotype0001429	granules_cytoplasm	1	0	1
> WBPhenotype0001259	hermaphrodite_fertility_reduced	1	1	0
> WBPhenotype0000800	posterior_region_development_abnormal	1	1	0
> WBPhenotype0000208	long_defecation_cycle	1	1	0
> WBPhenotype0001437	octanol_chemotaxis_hypersensitive	1	0	1
> WBPhenotype0000740	cell_cycle_abnormal	1	1	0
> WBPhenotype0000766	 
> centrosome_pair_and_associated_pronuclear_rotation_abnormal	1	1	0
> WBPhenotype0001042	neuron_function_reduced	1	0	1
> WBPhenotype0001511	linker_cell_migration_abnormal	1	0	1
> WBPhenotype0000494	two_fold_arrest	1	0	1
> WBPhenotype0001174	chromosome_disjunction_abnormal	1	0	1
> WBPhenotype0000400	somatic_gonad_primordium_development_defective	1	 
> 1	0
> WBPhenotype0000876	organism_osmotic_stress_response_abnormal	1	0	1
> WBPhenotype0001303	ectopic_cell	1	0	1
> WBPhenotype0001493	VPC_cell_division_precocious	1	0	1
> WBPhenotype0000576	organism_physiology_abnormal	1	1	0
> WBPhenotype0000549	head_muscle_dystrophy	1	0	1
> WBPhenotype0000665	connection_of_gonad_abnormal	1	0	1
> WBPhenotype0000166	seam_cell_fusion_abnormal	1	1	0
> WBPhenotype0000021	squat	1	1	0
> WBPhenotype0000846	presynaptic_region_physiology_abnormal	1	1	0
> WBPhenotype0001478	body_elongation_abnormal	1	1	0
> WBPhenotype0000916	excretory_cell_morphology_abnormal	1	0	1
> WBPhenotype0000981	spermatocyte_meiosis_abnormal	1	1	0
> WBPhenotype0001403	antibody_subcellular_localization_abnormal	1	0	1
> WBPhenotype0001396	pumping_absent	1	0	1
> WBPhenotype0001322	vesicle_number_reduced	1	0	1
> WBPhenotype0001279	transgene_expression_reduced_male	1	0	1
> WBPhenotype0000313	meiotic_progression_during_oogenesis_abnormal	1	1	0
> WBPhenotype0000847	presynaptic_component_localization_abnormal	1	0	1
> WBPhenotype0001258	RNAi_enhanced	1	0	1
> WBPhenotype0001281	stuffed_pharynx	1	0	1
> WBPhenotype0001394	cell_acidification_defective	1	0	1
> WBPhenotype0000649	vulva_location_abnormal	1	0	1
> WBPhenotype0000243	engulfment_failure_by_killer	1	0	1
> WBPhenotype0000669	sex_muscle_development_abnormal	1	0	1
> WBPhenotype0000509	sperm_pseudopod_abnormal	1	1	0
> WBPhenotype0000178	cell_degeneration	1	0	1
> WBPhenotype0000205	expulsion_abnormal	1	1	0
> WBPhenotype0000973	homologous_recombination_increased	1	0	1
> WBPhenotype0001246	no_transport_distal_segment_cilia	1	0	1
> WBPhenotype0001395	body_vacuole	1	0	1
> WBPhenotype0001099	nose_twisted	1	1	0
> WBPhenotype0000389	hermaphrodite_sperm_fertilization_defective	1	0	1
> WBPhenotype0000900	germ_cell_morphology_abnormal	1	1	0
> WBPhenotype0000337	grinder_relaxation_defective	1	0	1
> WBPhenotype0000455	jerky_movement	1	0	1
> WBPhenotype0001425	receptor_mediated_endocytosis_defective	1	1	0
> WBPhenotype0000000	chromosome_instability	1	1	0
> WBPhenotype0000546	early_eggs_laid	1	1	0
> WBPhenotype0000977	somatic_gonad_morphology_abnormal	1	0	1
> WBPhenotype0000094	anus_development_abnormal	1	1	0
> WBPhenotype0000399	somatic_gonad_development_abnormal	1	0	1
> WBPhenotype0000103	gut_granule_development_abnormal	1	1	0
> WBPhenotype0001319	endogenous_synaptic_event_frequency_reduced	1	0	1
> WBPhenotype0001215	germ_cell_mitosis_abnormal	1	1	0
> WBPhenotype0000968	tail_spike	1	0	1
> WBPhenotype0000681	DMPP_response_abnormal	1	0	1
> WBPhenotype0001090	thermotolerance_reduced	1	0	1
> WBPhenotype0001164	excess_pronucleus_early_emb	1	1	0
> WBPhenotype0001454	quinine_chemotaxis_abnormal	1	1	0
> WBPhenotype0000279	spicule_insertion_defective	1	1	0
> WBPhenotype0000366	three_fold_arrest	1	1	0
> WBPhenotype0000210	defecation_contraction_abnormal	1	0	1
> WBPhenotype0000925	sex_muscle_morphology_abnormal	1	0	1
> WBPhenotype0000997	cryophilic	1	0	1
> WBPhenotype0000755	L1_L2_molt_abnormal	1	1	0
> WBPhenotype0000328	terminal_bulb_contraction_abnormal	1	0	1
> WBPhenotype0000353	backing_increased	1	0	1
> WBPhenotype0000322	nose_rounded	1	0	1
> WBPhenotype0000116	mid_larval_lethal	1	0	1
> WBPhenotype0000654	synaptic_vesicle_exocytosis_abnormal	1	0	1
> WBPhenotype0000585	cell_homeostasis_metabolism_abnormal	1	0	1
> WBPhenotype0001526	ciliated_neuron_abnormal	1	0	1
> WBPhenotype0001022	hermaphrodite_sexual_development_abnormal	1	0	1
> WBPhenotype0000253	movement_erratic	1	0	1
> WBPhenotype0000336	terminal_bulb_relaxation_abnormal	1	0	1
> WBPhenotype0000063	terminal_arrest_variable	1	0	1

