version: "3.7"
services:
  db:
    container_name: curation_db
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
      POSTGRES_PORT: ${PSQL_PORT}
      TZ: 'US/Pacific'
      PGTZ: 'US/Pacific'
    ports:
      - "${PSQL_PORT}:${PSQL_PORT}"
    command: postgres -c config_file=/etc/postgresql.conf -c hba_file=/etc/pg_hba.conf
    volumes:
      - "./db/postgresql.conf:/etc/postgresql.conf"
      - "./db/pg_hba.conf:/etc/pg_hba.conf"
      - curation_db_storage:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PSQL_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - caltech-curation-network
    hostname: curation_db

  postgres_prom_exporter:
    container_name: postgres_prom_exporter
    image: wrouesnel/postgres_exporter
    environment:
      DATA_SOURCE_URI: curation_db:${PSQL_PORT}?sslmode=disable
      DATA_SOURCE_USER: ${PSQL_USERNAME}
      DATA_SOURCE_PASS: ${PSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - caltech-curation-network
    hostname: postgres_prom_exporter

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - postgres_prom_exporter
    networks:
      - caltech-curation-network
    hostname: prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - db
      - prometheus
    networks:
      - caltech-curation-network

  curation_forms:
    container_name: curation_forms
    build:
      context: .
      dockerfile: curation_forms/Dockerfile
    ports:
      - "${CURATION_FORMS_PORT}:80"
    volumes:
      - "${HTTPD_AUTH_FILE_PATH}:/etc/httpd/passwd/passwords"
      - "${CURATION_FORMS_USER_FILES_LOCATION}:/etc/user_files"
    depends_on:
      - db
    networks:
      - caltech-curation-network
    hostname: curation_forms

networks:
  caltech-curation-network:
    name: caltech-curation-network

volumes:
  grafana_storage:
  curation_db_storage:
