global:
  config_version: 3
input:
  type: file
  path: /grok/log/afp/afp_reminder_email.log
  readall: true
  poll_interval_seconds: 5
imports:
- type: grok_patterns
  dir: ./patterns
metrics:
- type: counter
  name: afp_reminders_num_errors
  help: Number of errors in the AFP email reminder emails pipeline
  match: '(.*Traceback.*)|(Segmentation fault.*)'
  labels:
    logfile: '{{base .logfile}}'
- type: counter
  name: afp_reminders_num_successes
  help: Number of successful runs
  match: 'Pipeline finished successfully'
  labels:
    logfile: '{{base .logfile}}'
server:
  port: 9144
