global:
  config_version: 3
input:
  type: file
  path: /grok/log/ntt_extr/antibody/antibody_ext_pipeline.log
  readall: true
  poll_interval_seconds: 5
imports:
- type: grok_patterns
  dir: ./patterns
metrics:
- type: counter
  name: ntt_extr_antibody_num_errors
  help: Error counter
  match: '(.*Traceback.*)|(Segmentation fault.*)'
  labels:
    logfile: '{{base .logfile}}'
- type: counter
  name: ntt_extr_antibody_num_processed_papers
  help: Number of WB papers processed by the pipeline
  match: '.*Extracting antibody info from paper.*'
  labels:
    logfile: '{{base .logfile}}'
- type: counter
  name: ntt_extr_antibody_num_extracted_papers
  help: Number of WB papers with antibody data extracted by the pipeline
  match: '.*Values for paper.*'
  labels:
    logfile: '{{base .logfile}}'
- type: counter
  name: ntt_extr_antibody_num_successes
  help: Number of successful runs
  match: 'Finished'
  labels:
    logfile: '{{base .logfile}}'
server:
  port: 9144
