global:
  config_version: 3
input:
  type: file
  path: /grok/log/vfp/vfp_pipeline.log
  readall: true
  poll_interval_seconds: 5
imports:
- type: grok_patterns
  dir: ./patterns
metrics:
- type: counter
  name: vfp_num_errors 
  help: Error counter
  match: '(.*Traceback.*)|(Segmentation fault.*)'
  labels:
    logfile: '{{base .logfile}}'
- type: counter
  name: vfp_num_processed_papers
  help: Number of WB papers processed by the pipeline
  match: '.*Loading paper.*'
  labels:
    logfile: '{{base .logfile}}'
- type: counter
  name: vfp_num_successes
  help: Number of successful runs
  match: 'Pipeline finished successfully'
  labels:
    logfile: '{{base .logfile}}'
server:
  port: 9144
