global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'web.hook'
    webhook_configs:
    - url: 'http://127.0.0.1:5001/'
  - name: 'email'
    email_configs:
    - to: '<alert_recipient>'
      from: '<from_address>'
      smarthost: host:port
      auth_username: '<from_address>'
      auth_identity: '<from_address>'
      auth_password: '<password>'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
