#!/usr/bin/perl -w

# Table of CGCs, PMIDs, MEDs, etc. and corresponding WBPaper IDs.
#
# Just look at the postgreSQL database for table correlation data  2005 06 10
#
# Write to /home/acedb/public_html/paper2wbpaper.txt
# Added to crontab -e 
# 0 2 * * mon,tue,wed,thu,fri,sat,sun /home/acedb/public_html/updatePaper2wbpaper.pl
# 2005 06 10
#
# Changed to pap_ tables (although they're not yet live)  2010 06 22
# 
# 0 2 * * mon,tue,wed,thu,fri,sat,sun /home/acedb/public_html/updatePaper2wbpaper.pl
#
# Removed from crontab, Mary Ann was using the output, but will now use the wpa_xref.cgi
# http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/wpa_xref.cgi
# 2011 06 07


use strict;
use CGI;
use DBI;

my $dbh = DBI->connect ( "dbi:Pg:dbname=testdb", "", "") or die "Cannot connect to database!\n"; 
use Jex;

my $query = new CGI;

# my %wpaHash;
my %papHash;

# our %pmHash;
# our %cgcHash;
# our %checkedoutHash;
# our %medHash;		# hash of cgc-medline xref
# our %cgcHash;		# hash of cgc-medline xref
# our %wbHash;		# hash of cgc-medline xref

# my $result = $conn->exec( "SELECT wpa_timestamp FROM wpa_xref ORDER BY wpa_timestamp DESC;" ); 
# my $result = $conn->exec( "SELECT wpa_timestamp FROM wpa_identifier ORDER BY wpa_timestamp DESC;" ); 
# my $result = $dbh->prepare( "SELECT wpa_timestamp FROM wpa_identifier ORDER BY wpa_timestamp DESC;" ); 
my $result = $dbh->prepare( "SELECT pap_timestamp FROM pap_identifier ORDER BY pap_timestamp DESC;" ); 
$result->execute() or die "Cannot prepare statement: $DBI::errstr\n"; 
my @row = $result->fetchrow;
my $date = $row[0];
$date =~ s/\..*$//;


# &printHeader('WBPaper Xref Table');			# print the HTML header
# &PrintHeader();				# print the HTML header
&populateHashes();
&display();
# &printFooter();			# print the HTML footer

sub display {
#   print "<TABLE border=1 cellspacing=5>\n";
#   print "<TR><TD ALIGN=CENTER>WBPaper</TD><TD ALIGN=CENTER>Other</TD></TR>\n";
  my $outfile = '/home/acedb/public_html/paper2wbpaper.txt';
  open (OUT, ">$outfile") or die "Cannot create $outfile : $!";
  print OUT "\/\/ Last connection made on $date.  Generated by cronjob, For up-to-date entries see http://tazendra.caltech.edu/~postgres/cgi-bin/wpa_xref_backwards.cgi\n";
  foreach my $pap (sort keys %papHash) { 
    foreach my $other (sort keys %{ $papHash{$pap} }) { 
      print OUT "$other\tWBPaper$pap\n";
    } # foreach $other (sort keys %{ $papHash{$pap} })
  } # foreach $pap_ (sort keys %cgcHash)
  close (OUT) or die "Cannot close $outfile : $!";
#   print "</TABLE>\n";
} # sub display 

sub populateHashes {
#   my $result = $conn->exec( "SELECT * FROM wpa_xref;" ); 
#   my $result = $conn->exec( "SELECT * FROM wpa_identifier;" ); 
#   my $result = $dbh->prepare( "SELECT * FROM wpa_identifier;" ); 
  my $result = $dbh->prepare( "SELECT * FROM pap_identifier;" ); 
  $result->execute() or die "Cannot prepare statement: $DBI::errstr\n"; 
  my @row;
  while (@row = $result->fetchrow) {	# loop through all rows returned
    $papHash{$row[0]}{$row[1]}++;
  } # while (my @row = $result->fetchrow) 
} # sub populateHashes 

# sub display {
#   print "<TABLE border=1 cellspacing=5>\n";
#   print "<TR><TD ALIGN=CENTER>cgc</TD><TD ALIGN=CENTER>pmid</TD></TR>\n";
#   foreach $_ (sort keys %cgcHash) { 
#     print "<TR><TD ALIGN=CENTER>$_</TD><TD ALIGN=CENTER>$cgcHash{$_}</TD></TR>\n";
#   } # foreach $_ (sort keys %cgcHash)
#   foreach $_ (sort keys %medHash) { 
#     print "<TR><TD ALIGN=CENTER>$_</TD><TD ALIGN=CENTER>$medHash{$_}</TD></TR>\n";
#   } # foreach $_ (sort keys %medHash)
#   foreach $_ (sort keys %cgcHash) { 
#     print "<TR><TD ALIGN=CENTER>$_</TD><TD ALIGN=CENTER>$cgcHash{$_}</TD></TR>\n";
#   } # foreach $_ (sort keys %cgcHash)
#   foreach $_ (sort keys %wbHash) { 
#     print "<TR><TD ALIGN=CENTER>$_</TD><TD ALIGN=CENTER>$wbHash{$_}</TD></TR>\n";
#   } # foreach $_ (sort keys %wbHash)
#   print "</TABLE>\n";
# } # sub display
# 
# sub populateHashes {
#   my $result = $conn->exec( "SELECT * FROM ref_xref;" ); 
#   my @row;
#   while (@row = $result->fetchrow) {	# loop through all rows returned
#     $cgcHash{$row[0]} = $row[1];
#     $pmHash{$row[1]} = $row[0];
#   } # while (my @row = $result->fetchrow) 
#   $result = $conn->exec ( "SELECT * FROM ref_checked_out;" );
#   while (@row = $result->fetchrow) {
#     $checkedoutHash{$row[0]} = $row[1];
#   } # while (@row = $result->fetchrow)
#   $result = $conn->exec ( "SELECT * FROM ref_xrefmed;" );
#   while (@row = $result->fetchrow) {	# loop through all rows returned
#     $medHash{$row[0]} = $row[1];
#   } # while (@row = $result->fetchrow)
#   $result = $conn->exec ( "SELECT * FROM ref_xref_cgc;" );
#   while (@row = $result->fetchrow) {	# loop through all rows returned
#     $cgcHash{$row[0]} = $row[1];
#   } # while (@row = $result->fetchrow)
#   $result = $conn->exec ( "SELECT * FROM ref_ref_xref_wb_oldwb;" );
#   while (@row = $result->fetchrow) {	# loop through all rows returned
#     $wbHash{$row[0]} = $row[1];
#   } # while (@row = $result->fetchrow)
# } # sub populateHashes



sub PrintHeader {
  print <<"EndOfText";
Content-type: text/plain\n\n
// Last connection made on $date
EndOfText
} # sub PrintHeader 

