#!/usr/bin/perl5.6.0

use lib qw( /usr/lib/perl5/site_perl/5.6.1/i686-linux/ );
use Pg;

$conn = Pg::connectdb("dbname=testdb");
die $conn->errorMessage unless PGRES_CONNECTION_OK eq $conn->status;

$result = $conn->exec( "CREATE TABLE curator ( joinkey TEXT, curator TEXT )");
$result = $conn->exec( "CREATE TABLE newsymbol ( joinkey TEXT, newsymbol TEXT )");
$result = $conn->exec( "CREATE TABLE synonym ( joinkey TEXT, synonym TEXT )");
$result = $conn->exec( "CREATE TABLE mappingdata ( joinkey TEXT, mappingdata TEXT )");
$result = $conn->exec( "CREATE TABLE genefunction ( joinkey TEXT, genefunction TEXT )");
$result = $conn->exec( "CREATE TABLE associationequiv ( joinkey TEXT, associationequiv TEXT )");
$result = $conn->exec( "CREATE TABLE associationnew ( joinkey TEXT, associationnew TEXT )");
$result = $conn->exec( "CREATE TABLE expression ( joinkey TEXT, expression TEXT )");
$result = $conn->exec( "CREATE TABLE rnai ( joinkey TEXT, rnai TEXT )");
$result = $conn->exec( "CREATE TABLE transgene ( joinkey TEXT, transgene TEXT )");
$result = $conn->exec( "CREATE TABLE overexpression ( joinkey TEXT, overexpression TEXT )");
$result = $conn->exec( "CREATE TABLE mosaic ( joinkey TEXT, mosaic TEXT )");
$result = $conn->exec( "CREATE TABLE antibody ( joinkey TEXT, antibody TEXT )");
$result = $conn->exec( "CREATE TABLE extractedallelename ( joinkey TEXT, extractedallelename TEXT )");
$result = $conn->exec( "CREATE TABLE extractedallelenew ( joinkey TEXT, extractedallelenew TEXT )");
$result = $conn->exec( "CREATE TABLE newmutant ( joinkey TEXT, newmutant TEXT )");
$result = $conn->exec( "CREATE TABLE sequencechange ( joinkey TEXT, sequencechange TEXT )");
$result = $conn->exec( "CREATE TABLE genesymbols ( joinkey TEXT, genesymbols TEXT )");
$result = $conn->exec( "CREATE TABLE geneproduct ( joinkey TEXT, geneproduct TEXT )");
$result = $conn->exec( "CREATE TABLE structurecorrection ( joinkey TEXT, structurecorrection TEXT )");
$result = $conn->exec( "CREATE TABLE sequencefeatures ( joinkey TEXT, sequencefeatures TEXT )");
$result = $conn->exec( "CREATE TABLE cellname ( joinkey TEXT, cellname TEXT )");
$result = $conn->exec( "CREATE TABLE cellfunction ( joinkey TEXT, cellfunction TEXT )");
$result = $conn->exec( "CREATE TABLE ablationdata ( joinkey TEXT, ablationdata TEXT )");
$result = $conn->exec( "CREATE TABLE newsnp ( joinkey TEXT, newsnp TEXT )");
$result = $conn->exec( "CREATE TABLE stlouissnp ( joinkey TEXT, stlouissnp TEXT )");
$result = $conn->exec( "CREATE TABLE goodphoto ( joinkey TEXT, goodphoto TEXT )");
$result = $conn->exec( "CREATE TABLE comment ( joinkey TEXT, comment TEXT )");

$result = $conn->exec( "CREATE INDEX curator_idx ON curator ( joinkey )");
$result = $conn->exec( "CREATE UNIQUE INDEX newsymbol_idx ON newsymbol ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX synonym_idx ON synonym ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX mappingdata_idx ON mappingdata ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX genefunction_idx ON genefunction ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX associationequiv_idx ON associationequiv ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX associationnew_idx ON associationnew ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX expression_idx ON expression ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX rnai_idx ON rnai ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX transgene_idx ON transgene ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX overexpression_idx ON overexpression ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX mosaic_idx ON mosaic ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX antibody_idx ON antibody ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX extractedallelename_idx ON extractedallelename ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX extractedallelenew_idx ON extractedallelenew ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX newmutant_idx ON newmutant ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX sequencechange_idx ON sequencechange ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX genesymbols_idx ON genesymbols ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX geneproduct_idx ON geneproduct ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX structurecorrection_idx ON structurecorrection ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX sequencefeatures_idx ON sequencefeatures ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX cellname_idx ON cellname ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX cellfunction_idx ON cellfunction ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX ablationdata_idx ON ablationdata ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX newsnp_idx ON newsnp ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX stlouissnp_idx ON stlouissnp ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX goodphoto_idx ON goodphoto ( joinkey)");
$result = $conn->exec( "CREATE UNIQUE INDEX comment_idx ON comment ( joinkey)");

$result = $conn->exec( "GRANT ALL ON curator TO nobody" );
$result = $conn->exec( "GRANT ALL ON newsymbol TO nobody" );
$result = $conn->exec( "GRANT ALL ON synonym TO nobody" );
$result = $conn->exec( "GRANT ALL ON mappingdata TO nobody" );
$result = $conn->exec( "GRANT ALL ON genefunction TO nobody" );
$result = $conn->exec( "GRANT ALL ON associationequiv TO nobody" );
$result = $conn->exec( "GRANT ALL ON associationnew TO nobody" );
$result = $conn->exec( "GRANT ALL ON expression TO nobody" );
$result = $conn->exec( "GRANT ALL ON rnai TO nobody" );
$result = $conn->exec( "GRANT ALL ON transgene TO nobody" );
$result = $conn->exec( "GRANT ALL ON overexpression TO nobody" );
$result = $conn->exec( "GRANT ALL ON mosaic TO nobody" );
$result = $conn->exec( "GRANT ALL ON antibody TO nobody" );
$result = $conn->exec( "GRANT ALL ON extractedallelename TO nobody" );
$result = $conn->exec( "GRANT ALL ON extractedallelenew TO nobody" );
$result = $conn->exec( "GRANT ALL ON newmutant TO nobody" );
$result = $conn->exec( "GRANT ALL ON sequencechange TO nobody" );
$result = $conn->exec( "GRANT ALL ON genesymbols TO nobody" );
$result = $conn->exec( "GRANT ALL ON geneproduct TO nobody" );
$result = $conn->exec( "GRANT ALL ON structurecorrection TO nobody" );
$result = $conn->exec( "GRANT ALL ON sequencefeatures TO nobody" );
$result = $conn->exec( "GRANT ALL ON cellname TO nobody" );
$result = $conn->exec( "GRANT ALL ON cellfunction TO nobody" );
$result = $conn->exec( "GRANT ALL ON ablationdata TO nobody" );
$result = $conn->exec( "GRANT ALL ON newsnp TO nobody" );
$result = $conn->exec( "GRANT ALL ON stlouissnp TO nobody" );
$result = $conn->exec( "GRANT ALL ON goodphoto TO nobody" );
$result = $conn->exec( "GRANT ALL ON comment TO nobody" );
